gen:
	lcm-gen -x dynamixel_command_t.lcm; \
	lcm-gen -x dynamixel_command_list_t.lcm; \
	lcm-gen -x dynamixel_status_t.lcm; \
	lcm-gen -x dynamixel_status_list_t.lcm; \
	lcm-gen -x search_target_t.lcm;
